name: Build for .no domain

# on:
#   push:
#     branches: [main]

## Manual trigger only, uncomment above when deployment ready.

## This deployment file probably won't be needed, as it will be built locally,
## then uploaded to the .no-domain via an FTP-client.
## This "File Transfer Protocol" will let me upload files to my own .no-domain-folders.
## Leaving this YAML-file here anyways,
## as there might be a future use for automated deployment. – Jon
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - run: npm install
      - run: npm run build
        env:
          DEPLOY_TARGET: no
      - uses: actions/upload-artifact@v4
        with:
          name: dist-no
          path: dist/
